/**
 * ConfirmationStep.jsx — Step 3 of RegistrationModal (Official Registration Success).
 *
 * Flow & Gateway Rules:
 *  1. Only after payment is verified by the payment gateway, the official PAID receipt is unlocked.
 *  2. Automatically generates the receipt PDF after successful payment verification.
 *  3. Displays Download Receipt and Print Receipt buttons.
 *  4. Contains all 11 required fields:
 *     Receipt Number, Date, Payment Status, Team Name, Team Leader, Registration ID,
 *     Event Name, Applicable Fees, Total Paid Amount, Transaction ID, Payment Method.
 *  5. Includes Success Squad and E-Fest logos from EFEST RECEIPT-SP.pdf reference.
 *  6. Never marks failed or pending payments as PAID.
 */

import { useState, useEffect, useCallback, useRef } from 'react'
import { Link } from 'react-router-dom'
import {
  getPendingPaymentByOrderId,
  getRegistrationByOrderId,
  subscribeToOrderStatus,
  verifyAndSavePaymentGateway,
} from '../../../services/registrations.js'
import { generateReceipt, printReceipt, resolveEventName, formatReceiptDate } from '../../../utils/generateReceipt.js'

export default function ConfirmationStep({ config, formData, paymentResult, onClose }) {
  // Initialize order state
  const [order, setOrder] = useState(() => {
    if (!paymentResult) return null
    const isInitVerified =
      paymentResult.status === 'verified' ||
      paymentResult.status === 'confirmed' ||
      paymentResult.payment_status === 'PAID'

    return {
      order_id: paymentResult.orderId || paymentResult.order_id,
      event_id: config?.id || paymentResult.eventId || paymentResult.event_id,
      team_data: formData || paymentResult.team_data,
      amount_inr: config?.entryFee ?? paymentResult.amount_inr ?? 199,
      utr: paymentResult.utr || '—',
      created_at: paymentResult.created_at || new Date().toISOString(),
      verified_at: paymentResult.verified_at || (isInitVerified ? new Date().toISOString() : null),
      status: paymentResult.status || (isInitVerified ? 'verified' : 'submitted'),
      payment_status: isInitVerified ? 'PAID' : 'PENDING',
      team_id: paymentResult.team_id || paymentResult.registration_id || null,
      registration_id: paymentResult.team_id || paymentResult.registration_id || null,
      receipt_number: paymentResult.receipt_number || null,
      payment_method: paymentResult.payment_method || 'UPI / Online Payment Gateway',
      ...paymentResult,
    }
  })

  const [downloading, setDownloading]           = useState(false)
  const [printing, setPrinting]                 = useState(false)
  const [verifyingGateway, setVerifyingGateway] = useState(false)
  const [autoGenerated, setAutoGenerated]       = useState(false)
  const [downloadSuccess, setDownloadSuccess]   = useState(false)
  const [actionError, setActionError]           = useState('')
  const [copiedId, setCopiedId]                 = useState(false)

  const isVerified = Boolean(
    order &&
    (order.status === 'verified' ||
      order.status === 'confirmed' ||
      order.payment_status === 'PAID')
  )

  const autoGenTriggered = useRef(false)

  // ── Sync with Supabase & Listen to Realtime Status Updates ─────────────────
  useEffect(() => {
    const orderId = order?.order_id || paymentResult?.orderId
    if (!orderId) return

    let mounted = true

    // Check if registration row already exists in Supabase
    const syncDb = async () => {
      try {
        const [regData, pendingData] = await Promise.all([
          getRegistrationByOrderId(orderId).catch(() => null),
          getPendingPaymentByOrderId(orderId).catch(() => null),
        ])

        if (mounted && (regData || pendingData)) {
          setOrder((prev) => {
            const merged = {
              ...(prev || {}),
              ...(pendingData || {}),
              ...(regData || {}),
              team_data: regData?.team_data || pendingData?.team_data || prev?.team_data || formData,
            }

            if (regData || merged.status === 'verified' || merged.status === 'confirmed') {
              merged.status = 'verified'
              merged.payment_status = 'PAID'
            }
            return merged
          })
        }
      } catch (err) {
        console.warn('DB sync notice:', err)
      }
    }

    syncDb()

    // Realtime Supabase listener
    const unsubscribe = subscribeToOrderStatus(orderId, (updatedRow) => {
      if (!mounted || !updatedRow) return
      setOrder((prev) => {
        const isNowVerified = updatedRow.status === 'verified' || updatedRow.status === 'confirmed'
        return {
          ...(prev || {}),
          ...updatedRow,
          status: isNowVerified ? 'verified' : updatedRow.status,
          payment_status: isNowVerified ? 'PAID' : prev?.payment_status,
        }
      })
    })

    return () => {
      mounted = false
      if (typeof unsubscribe === 'function') unsubscribe()
    }
  }, [paymentResult?.orderId, order?.order_id, formData])

  // ── Automatic Receipt Generation Upon Payment Verification ─────────────────
  useEffect(() => {
    if (!isVerified || !order || autoGenTriggered.current) return

    autoGenTriggered.current = true
    let isMounted = true

    const autoGen = async () => {
      try {
        // Pre-generate receipt PDF without triggering browser download
        await generateReceipt(order, { download: false })
        if (isMounted) {
          setAutoGenerated(true)
        }
      } catch (err) {
        console.warn('Pre-rendering receipt:', err)
      }
    }

    autoGen()

    return () => {
      isMounted = false
    }
  }, [isVerified, order])

  // ── Manual / On-Demand Gateway Verification ────────────────────────────────
  const handleVerifyWithGateway = useCallback(async () => {
    if (!order) return
    setVerifyingGateway(true)
    setActionError('')

    try {
      const verified = await verifyAndSavePaymentGateway({
        orderId:       order.order_id,
        utr:           order.utr,
        eventId:       order.event_id || config?.id,
        teamData:      order.team_data || formData,
        amountINR:     order.amount_inr || config?.entryFee,
        paymentMethod: order.payment_method || 'UPI / Online Payment Gateway',
        screenshotUrl: order.screenshot_url || null,
      })

      setOrder((prev) => ({
        ...(prev || {}),
        ...verified,
        status: 'verified',
        payment_status: 'PAID',
      }))
    } catch (err) {
      console.error('Gateway verification failed:', err)
      setActionError(err.message || 'Payment verification failed. Please check your Transaction ID.')
    } finally {
      setVerifyingGateway(false)
    }
  }, [order, config, formData])

  // ── Download Receipt Handler ───────────────────────────────────────────────
  const handleDownloadReceipt = async () => {
    if (!order) return
    if (!isVerified) {
      setActionError('Receipt can only be generated after payment is verified by the payment gateway.')
      return
    }

    setDownloading(true)
    setActionError('')

    try {
      await generateReceipt(order, { download: true })
      setDownloadSuccess(true)
      setTimeout(() => setDownloadSuccess(false), 5000)
    } catch (err) {
      console.error('Download receipt error:', err)
      setActionError('Could not download receipt: ' + (err.message || 'Please try again.'))
    } finally {
      setDownloading(false)
    }
  };

  // ── Print Receipt Handler ──────────────────────────────────────────────────
  const handlePrintReceipt = async () => {
    if (!order) return
    if (!isVerified) {
      setActionError('Receipt can only be printed after payment is verified by the payment gateway.')
      return
    }

    setPrinting(true)
    setActionError('')

    try {
      await printReceipt(order)
    } catch (err) {
      console.error('Print receipt error:', err)
      setActionError('Could not open print preview: ' + (err.message || 'Please try again.'))
    } finally {
      setPrinting(false)
    }
  }

  // ── Copy Registration / Order ID ───────────────────────────────────────────
  const handleCopyId = (text) => {
    if (!text) return
    navigator.clipboard?.writeText(text)
    setCopiedId(true)
    setTimeout(() => setCopiedId(false), 2500)
  }

  if (!order) {
    return (
      <div className="reg-confirmation" style={{ padding: '60px 0', gap: 16 }}>
        <span className="reg-spinner" style={{ width: 32, height: 32, borderWidth: 3 }} aria-label="Loading" />
        <p style={{ color: 'var(--text-muted)' }}>Loading confirmation details…</p>
      </div>
    )
  }

  const teamName       = order.team_data?.teamName ?? formData?.teamName ?? '—'
  const leaderName     = order.team_data?.leaderName ?? formData?.leaderName ?? '—'
  const eventTitle     = resolveEventName(order.event_id || config?.id)
  const displayId      = order.team_id || order.registration_id || order.order_id
  const receiptNum     = order.receipt_number || `EF26-REC-${order.order_id ? order.order_id.replace(/^ORD_/, '') : 'CONFIRMED'}`
  const formattedDate  = formatReceiptDate(order.verified_at || order.created_at)
  const amountDisplay  = `₹${order.amount_inr ?? config?.entryFee ?? 199}`
  const payMethod      = order.payment_method || 'UPI / Online Payment Gateway'

  return (
    <div className="reg-confirmation" aria-live="polite">
      {/* ── TOP HEADER STATE (VERIFIED SUCCESS vs AWAITING VERIFICATION) ── */}
      {isVerified ? (
        <>
          <div className="reg-confirmation-icon" aria-hidden="true" style={{ fontSize: '3rem', marginBottom: 10 }}>
            🎉
          </div>
          <h3 className="reg-step-title" style={{ color: '#10b981', marginBottom: 6 }}>
            Payment Verified & Registration Confirmed!
          </h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.92rem', maxWidth: 440, margin: '0 auto 18px', lineHeight: 1.5 }}>
            Your payment has been officially verified by the payment gateway. Your official E-Fest '26 registration receipt has been generated below.
          </p>
        </>
      ) : (
        <>
          <div className="reg-confirmation-icon" aria-hidden="true" style={{ fontSize: '3rem', marginBottom: 10 }}>
            ⏳
          </div>
          <h3 className="reg-step-title" style={{ color: '#fbbf24', marginBottom: 6 }}>
            Payment Submitted · Awaiting Verification
          </h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.92rem', maxWidth: 440, margin: '0 auto 18px', lineHeight: 1.5 }}>
            Your payment proof has been submitted. In accordance with festival policy, official receipts are generated only after gateway verification.
          </p>
        </>
      )}

      {/* ── REGISTRATION / ORDER ID HIGHLIGHT BOX ── */}
      <div
        className="reg-teamid-box"
        style={{
          border: isVerified ? '1px solid rgba(16, 185, 129, 0.4)' : '1px solid rgba(245, 158, 11, 0.4)',
          background: isVerified ? 'rgba(16, 185, 129, 0.08)' : 'rgba(245, 158, 11, 0.08)',
        }}
        aria-label={`Your ID is ${displayId}`}
      >
        <span className="reg-teamid-label" style={{ color: isVerified ? '#10b981' : '#fbbf24' }}>
          {isVerified ? 'Official Registration ID' : 'Order ID (Pending Verification)'}
        </span>
        <span className="reg-teamid-value" id="confirmed-registration-id" style={{ fontSize: '1.25rem', letterSpacing: 1.5 }}>
          {displayId}
        </span>
        <button
          className="reg-teamid-copy btn btn-ghost"
          onClick={() => handleCopyId(displayId)}
          aria-label="Copy Registration ID"
          id="copy-registration-id-btn"
        >
          {copiedId ? '✓ Copied' : 'Copy'}
        </button>
      </div>

      {/* ── PAYMENT & RECEIPT DETAILS SUMMARY (Exact 11 Fields) ── */}
      <div
        className="receipt-placeholder"
        style={{
          marginTop: 18,
          width: '100%',
          textAlign: 'left',
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid var(--border)',
          borderRadius: 14,
          padding: 20,
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <span style={{ fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: 2, color: 'var(--text-muted)' }}>
            Payment & Registration Details
          </span>
          <span
            style={{
              fontSize: '0.75rem',
              fontWeight: 900,
              padding: '3px 10px',
              borderRadius: 4,
              letterSpacing: 1,
              background: isVerified ? '#5cb85c' : '#f59e0b',
              color: '#000000',
              textTransform: 'uppercase',
            }}
          >
            {isVerified ? 'PAID' : 'PENDING GATEWAY'}
          </span>
        </div>

        {[
          ['Receipt Number',    isVerified ? receiptNum : 'Issued upon verification'],
          ['Date',              formattedDate],
          ['Payment Status',    isVerified ? 'PAID (Verified)' : 'Pending Verification'],
          ['Team Name',         teamName],
          ['Team Leader',       leaderName],
          ['Registration ID',   displayId],
          ['Event Name',        eventTitle],
          ['Applicable Fees',   amountDisplay],
          ['Total Paid Amount', amountDisplay],
          ['Transaction ID',    order.utr || '—'],
          ['Payment Method',    payMethod],
        ].map(([label, value]) => (
          <div
            key={label}
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'baseline',
              padding: '6px 0',
              borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
              fontSize: '0.86rem',
            }}
          >
            <span style={{ color: 'var(--text-muted)' }}>{label}</span>
            <strong style={{ maxWidth: '62%', textAlign: 'right', wordBreak: 'break-word', color: '#f3f4f6' }}>
              {value}
            </strong>
          </div>
        ))}
      </div>

      {/* ── ACTION ERROR BANNER ── */}
      {actionError && (
        <div
          role="alert"
          style={{
            marginTop: 14,
            padding: '10px 14px',
            background: 'rgba(239, 68, 68, 0.12)',
            border: '1px solid rgba(239, 68, 68, 0.35)',
            borderRadius: 8,
            color: '#fca5a5',
            fontSize: '0.85rem',
            textAlign: 'left',
            lineHeight: 1.4,
            width: '100%',
          }}
        >
          ⚠️ {actionError}
        </div>
      )}

      {/* ── IF UNVERIFIED: GATEWAY VERIFICATION TRIGGER ── */}
      {!isVerified && (
        <div style={{ marginTop: 18, width: '100%' }}>
          <button
            type="button"
            className="btn btn-primary"
            style={{
              width: '100%',
              padding: '13px 20px',
              fontSize: '0.98rem',
              fontWeight: 700,
              background: 'linear-gradient(135deg, #6366f1, #4f46e5)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
            }}
            onClick={handleVerifyWithGateway}
            disabled={verifyingGateway}
            id="verify-gateway-btn"
          >
            {verifyingGateway ? (
              <>
                <span className="reg-spinner" style={{ width: 18, height: 18, borderWidth: 2 }} aria-hidden="true" />
                Verifying with Payment Gateway…
              </>
            ) : (
              <>⚡ Verify with Payment Gateway</>
            )}
          </button>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', textAlign: 'center', marginTop: 8 }}>
            Receipt with <strong>PAID</strong> status will be automatically generated once verified.
          </p>
        </div>
      )}

      {/* ── IF VERIFIED: DOWNLOAD & PRINT RECEIPT BUTTONS ── */}
      {isVerified && (
        <div style={{ marginTop: 20, width: '100%', display: 'flex', flexDirection: 'column', gap: 12 }}>
          {autoGenerated && (
            <div
              style={{
                fontSize: '0.8rem',
                color: '#10b981',
                textAlign: 'center',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 6,
                background: 'rgba(16, 185, 129, 0.08)',
                padding: '6px 12px',
                borderRadius: 6,
              }}
            >
              <span>✓</span> Receipt PDF automatically generated from official reference
            </div>
          )}

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            {/* Download Receipt Button */}
            <button
              type="button"
              className="btn btn-primary"
              style={{
                padding: '13px 16px',
                fontSize: '0.94rem',
                fontWeight: 700,
                background: 'linear-gradient(135deg, #10b981, #059669)',
                border: 'none',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 8,
                boxShadow: '0 4px 16px rgba(16, 185, 129, 0.3)',
                cursor: downloading ? 'wait' : 'pointer',
              }}
              onClick={handleDownloadReceipt}
              disabled={downloading}
              id="download-receipt-btn"
            >
              {downloading ? (
                <>
                  <span className="reg-spinner" style={{ width: 16, height: 16, borderWidth: 2 }} aria-hidden="true" />
                  Generating…
                </>
              ) : downloadSuccess ? (
                <>✓ Downloaded!</>
              ) : (
                <>⬇ Download Receipt</>
              )}
            </button>

            {/* Print Receipt Button */}
            <button
              type="button"
              className="btn btn-secondary"
              style={{
                padding: '13px 16px',
                fontSize: '0.94rem',
                fontWeight: 700,
                border: '1px solid rgba(255, 255, 255, 0.2)',
                background: 'rgba(255, 255, 255, 0.08)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 8,
                cursor: printing ? 'wait' : 'pointer',
              }}
              onClick={handlePrintReceipt}
              disabled={printing}
              id="print-receipt-btn"
            >
              {printing ? (
                <>
                  <span className="reg-spinner" style={{ width: 16, height: 16, borderWidth: 2 }} aria-hidden="true" />
                  Preparing Print…
                </>
              ) : (
                <>🖨️ Print Receipt</>
              )}
            </button>
          </div>
        </div>
      )}

      {/* ── FOOTER ACTIONS ── */}
      <div className="reg-footer-actions" style={{ marginTop: 24, justifyContent: 'center', width: '100%' }}>
        <button className="btn btn-ghost" onClick={onClose} id="confirmation-close-btn">
          Close
        </button>
        <Link to="/status" className="btn btn-secondary" onClick={onClose} id="view-status-link">
          Check Status →
        </Link>
      </div>
    </div>
  )
}
